@startuml
'https://plantuml.com/use-case-diagram
left to right direction

actor User
actor System

package Auth {
    usecase Login
    usecase CreateAccount
    usecase Logout
    usecase VerifyAccount
    usecase ConfirmEmail
    usecase ConfirmIdentity
    usecase SetPin
}

package News {
    usecase CreateNews
    usecase EditNews
    usecase DeleteNews
}

package Transactions {
    usecase SeeTransactionSummary
    usecase SeeTransactionsByMonth
    usecase SeeTopTransactionsByMonth
    usecase SeeTopTransactionsByCategoryAndMonth
    usecase SeeRecentTransfers
    usecase TransferToAccount
    usecase SeeTransactionReceipt
}

package Profile {
    usecase SeeProfileCompleteness
    usecase SeeProfileQrCode
}

package Contacts {
    usecase SeeContacts
    usecase AddContact
    usecase EditContact
    usecase DeleteContact
    usecase InviteContact
}

package Account {
    usecase SeeAvailableBalance
    usecase SeeCurrentMonthBalance
    usecase SeeFinanceScore
    usecase SeeFinanceRecommendations
    usecase SeeFinanceRecommendationDetails
    usecase SetMonthlySpendingLimit
    usecase LinkBankAccount
    usecase LinkCard
    usecase LinkOnlinePaymentAccount
}

package Card {
    usecase LockCard
    usecase ChangeCardPin
    usecase SetCardLimit
}

'Relations
System -> (CreateNews)
System -> (EditNews)
System -> (DeleteNews)

User -> (Login)
User -> (CreateAccount)
User -> (Logout)
User -> (VerifyAccount)
User -> (ConfirmEmail)
User -> (ConfirmIdentity)
User -> (SetPin)
User -> (SeeTransactionSummary)
User -> (SeeTransactionsByMonth)
User -> (SeeTopTransactionsByMonth)
User -> (SeeTopTransactionsByCategoryAndMonth)
User -> (SeeRecentTransfers)
User -> (TransferToAccount)
User -> (SeeTransactionReceipt)
User -> (SeeProfileCompleteness)
User -> (SeeProfileQrCode)
User -> (SeeContacts)
User -> (AddContact)
User -> (EditContact)
User -> (DeleteContact)
User -> (InviteContact)
User -> (SeeAvailableBalance)
User -> (SeeCurrentMonthBalance)
User -> (SeeFinanceScore)
User -> (SeeFinanceRecommendations)
User -> (SeeFinanceRecommendationDetails)
User -> (SetMonthlySpendingLimit)
User -> (LinkBankAccount)
User -> (LinkCard)
User -> (LinkOnlinePaymentAccount)
User -> (LockCard)
User -> (ChangeCardPin)
User -> (SetCardLimit)

@enduml
